package expertsystemgui;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.LayoutManager;
import java.awt.Toolkit;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import org.joda.time.DateTime;
import org.joda.time.Days;
import org.joda.time.Hours;
import org.joda.time.Minutes;
import org.joda.time.Seconds;


public class Window extends javax.swing.JFrame {
    
    public PrologConnection connection;
    private LinkedHashMap<String, List<String>> QandA = new LinkedHashMap<>();
    private List<String> solutions = new ArrayList<>();
    private SystemStateEnum systemState;
    
    public Window(String title) {
        super(title);
        initComponents();
        setFramePosition();
        readLastAccessFile();
        setSolutionListModel();
        setStartPanel();
    }
    
    private void setFramePosition(){        
        /*//center
        //Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        //this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2); 
        */
        
        //top-left
        this.setLocation(0,0);

        // fullscreen
        //setExtendedState(java.awt.Frame.MAXIMIZED_BOTH); 

    }
    
    private void setSolutionListModel(){
        DefaultListModel<String> listModel = new DefaultListModel<>();
        solutionsList.setModel(listModel);
    }
    
    private void readLastAccessFile() {
        try(BufferedReader bufferedReader = new BufferedReader(new FileReader(new File("lastAccess.txt")))){
            String s;
            s = bufferedReader.readLine();
            DateTime lastAccessDate = new DateTime(s);
            DateTime now = DateTime.now();
            int days = Days.daysBetween(lastAccessDate, now).getDays();
            int hours = Hours.hoursBetween(lastAccessDate, now).getHours() % 24;
            int minutes = Minutes.minutesBetween(lastAccessDate, now).getMinutes() % 60;
            int seconds = Seconds.secondsBetween(lastAccessDate, now).getSeconds() % 60;
            String message = "Ultima accesare a fost acum " +
                             (days != 0 ?(days + " zile, ") : "") +
                             (hours != 0 ? (hours + " ore, ") : "") + 
                             (minutes != 0 ? (minutes + " minute si ") : "") + 
                             (seconds+" secunde.");
            greetingMessageLabel.setText(message);
            updateLastAccessFile();
        } 
        catch (IOException ex) {
            String message = "";
            greetingMessageLabel.setText(message);
            updateLastAccessFile();
        }
        finally{
            
        }
    }
    
    private void updateLastAccessFile(){
        try (PrintWriter writer = new PrintWriter("lastAccess.txt", "UTF-8")) {
            DateTime now = DateTime.now();
            writer.println(now.toString());
        }
        catch(IOException ex){
            Logger.getLogger(MessageSender.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setStartPanel(){
        
        setFilenameWrongLabelText("");
        startLabel.setText("<html>Bine ați venit! Vă vom ajuta să găsiți conferința perfectă pentru dvs!");
        loadInfoLabel.setText("<html>Pentru a consulta sistemul expert, trebuie sa incarcati"
                + " fisierul cu reguli si fisierul care contine solutiile.</html>");
        
        systemState = SystemStateEnum.START;
        switchScreen();
        
    }
    
    public void setFilenameWrongLabelText(String wrongFilename){
        if(wrongFilename.equals(""))
            filenameWrongLabel.setText("");
        else
            filenameWrongLabel.setText("<html><font color=\"red\">Nu am putut găsi fișierul \""+wrongFilename+"\"!</font></html>");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionsRadioButtonGroup = new javax.swing.ButtonGroup();
        outputAreaPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        commandPanel = new javax.swing.JPanel();
        consultButton = new javax.swing.JButton();
        resetSystemButton = new javax.swing.JButton();
        questionsPanel = new javax.swing.JPanel();
        backToMenuButton = new javax.swing.JButton();
        optionsPanel = new javax.swing.JPanel();
        questionLabel = new javax.swing.JLabel();
        certaintyFactorComboBox = new javax.swing.JComboBox<>();
        certaintyFactorLabel = new javax.swing.JLabel();
        questionsRadioButtonPanel = new javax.swing.JPanel();
        answersScrollPane = new javax.swing.JScrollPane();
        answersTextArea = new javax.swing.JTextArea();
        solutionsScrollPane = new javax.swing.JScrollPane();
        solutionsList = new javax.swing.JList<>();
        proofScrollPane = new javax.swing.JScrollPane();
        proofTextPane = new javax.swing.JTextPane();
        noSolutionsLabel = new javax.swing.JLabel();
        startPanel = new javax.swing.JPanel();
        startLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        loadInfoLabel = new javax.swing.JLabel();
        rulesFilenameLabel = new javax.swing.JLabel();
        solutionsFilenameLabel = new javax.swing.JLabel();
        rulesFilenameTextField = new javax.swing.JTextField();
        solutionsFilenameTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        filenameWrongLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        greetingMessageLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        loadRulesButton = new javax.swing.JButton();

        outputTextArea.setColumns(20);
        outputTextArea.setLineWrap(true);
        outputTextArea.setRows(5);
        jScrollPane1.setViewportView(outputTextArea);

        javax.swing.GroupLayout outputAreaPanelLayout = new javax.swing.GroupLayout(outputAreaPanel);
        outputAreaPanel.setLayout(outputAreaPanelLayout);
        outputAreaPanelLayout.setHorizontalGroup(
            outputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, outputAreaPanelLayout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addGap(246, 246, 246))
        );
        outputAreaPanelLayout.setVerticalGroup(
            outputAreaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputAreaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        consultButton.setText("Consult ");
        consultButton.setEnabled(false);
        consultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultButtonActionPerformed(evt);
            }
        });

        resetSystemButton.setText("Reset system");
        resetSystemButton.setEnabled(false);
        resetSystemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetSystemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout commandPanelLayout = new javax.swing.GroupLayout(commandPanel);
        commandPanel.setLayout(commandPanelLayout);
        commandPanelLayout.setHorizontalGroup(
            commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commandPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(consultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(commandPanelLayout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(resetSystemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        commandPanelLayout.setVerticalGroup(
            commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commandPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(resetSystemButton)
                .addGap(47, 47, 47)
                .addComponent(consultButton))
        );

        questionsPanel.setVisible(false);

        backToMenuButton.setText("Back to menu");
        backToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 289, Short.MAX_VALUE)
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        questionLabel.setText("Question");

        certaintyFactorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "100", "95", "90", "85", "80", "75", "70", "65", "60", "55", "50", "45", "40", "35", "30", "25", "20", "10", "5", "0" }));

        certaintyFactorLabel.setText("Factor de certitudine");

        questionsRadioButtonPanel.setLayout(new javax.swing.BoxLayout(questionsRadioButtonPanel, javax.swing.BoxLayout.Y_AXIS));

        answersScrollPane.setVisible(false);

        answersTextArea.setColumns(20);
        answersTextArea.setLineWrap(true);
        answersTextArea.setRows(5);
        answersScrollPane.setViewportView(answersTextArea);

        solutionsScrollPane.setPreferredSize(new java.awt.Dimension(258, 100));

        solutionsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        solutionsList.setVisibleRowCount(-1);
        solutionsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                solutionsListValueChanged(evt);
            }
        });
        solutionsScrollPane.setViewportView(solutionsList);

        proofScrollPane.setViewportView(proofTextPane);

        noSolutionsLabel.setVisible(false);
        noSolutionsLabel.setText("Nu exista solutii!");

        javax.swing.GroupLayout questionsPanelLayout = new javax.swing.GroupLayout(questionsPanel);
        questionsPanel.setLayout(questionsPanelLayout);
        questionsPanelLayout.setHorizontalGroup(
            questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(solutionsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(proofScrollPane)
                .addGap(18, 18, 18)
                .addComponent(answersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(questionsPanelLayout.createSequentialGroup()
                .addGroup(questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(questionsPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(questionsPanelLayout.createSequentialGroup()
                        .addGroup(questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(questionsPanelLayout.createSequentialGroup()
                                .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE))
                            .addGroup(questionsPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(noSolutionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(certaintyFactorLabel)
                            .addComponent(backToMenuButton)
                            .addGroup(questionsPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(certaintyFactorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(125, 125, 125)))
                .addComponent(questionsRadioButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        questionsPanelLayout.setVerticalGroup(
            questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionsPanelLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionsPanelLayout.createSequentialGroup()
                        .addComponent(questionLabel)
                        .addGap(11, 11, 11)
                        .addGroup(questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(questionsPanelLayout.createSequentialGroup()
                                .addComponent(certaintyFactorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(certaintyFactorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(backToMenuButton)))
                        .addGap(18, 18, 18)
                        .addComponent(noSolutionsLabel)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionsPanelLayout.createSequentialGroup()
                        .addComponent(questionsRadioButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(questionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proofScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(answersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solutionsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        startLabel.setText("Start label");

        loadInfoLabel.setText("LoadInfo");

        rulesFilenameLabel.setText("Nume fișier reguli:");

        solutionsFilenameLabel.setText("Nume fișier soluții:");

        rulesFilenameTextField.setText("Rules.txt");

        solutionsFilenameTextField.setText("SolutionInfo.txt");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(loadInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(solutionsFilenameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rulesFilenameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(solutionsFilenameTextField)
                    .addComponent(rulesFilenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(loadInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rulesFilenameLabel)
                            .addComponent(rulesFilenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(solutionsFilenameLabel)
                            .addComponent(solutionsFilenameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))))
        );

        filenameWrongLabel.setText("wrong file name");
        jPanel2.add(filenameWrongLabel);

        greetingMessageLabel.setText("Mesaj de bun venit");
        jPanel3.add(greetingMessageLabel);

        loadRulesButton.setText("Încarcă");
        loadRulesButton.setPreferredSize(new java.awt.Dimension(250, 30));
        loadRulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadRulesButtonActionPerformed(evt);
            }
        });
        jPanel4.add(loadRulesButton);

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(startLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(startLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(900, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultButtonActionPerformed
        try {
            connection.messageSender.sendMessageToExpertSystem("command(consult)");
        
        } catch (InterruptedException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_consultButtonActionPerformed

    private void backToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMenuButtonActionPerformed
        // TODO add your handling code here:
        //switchToMenuView();
    }//GEN-LAST:event_backToMenuButtonActionPerformed

    private void resetSystemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetSystemButtonActionPerformed
        // TODO add your handling code here:    
        try {
            connection.messageSender.sendMessageToExpertSystem("command(reset)");
        
        } catch (InterruptedException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.questionLabel.setVisible(false);
        this.optionsPanel.setVisible(false);
        this.certaintyFactorLabel.setVisible(false);
        this.certaintyFactorComboBox.setVisible(false);
        this.consultButton.setEnabled(true);
        this.questionsRadioButtonPanel.removeAll();
        this.answersScrollPane.setVisible(false);
        this.proofTextPane.setText("");
        this.noSolutionsLabel.setVisible(false);
        
        DefaultListModel listModel = (DefaultListModel) solutionsList.getModel();
        listModel.removeAllElements();
        
        solutions.clear();
        QandA.clear();
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_resetSystemButtonActionPerformed

    private void solutionsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_solutionsListValueChanged
        // TODO add your handling code here:
        if (evt.getValueIsAdjusting() == false) {
            
            int index = solutionsList.getSelectedIndex();
            if (index == -1)
                return;
            
            String selectedSolution = solutionsList.getSelectedValue();
            
            getProofForSolution(selectedSolution);
        }
    }//GEN-LAST:event_solutionsListValueChanged

    private void loadRulesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadRulesButtonActionPerformed
        String rulesFilename = rulesFilenameTextField.getText();
        String solutionsFilename = solutionsFilenameTextField.getText();
        consultButton.setEnabled(true);
        resetSystemButton.setEnabled(true);
        String dir = System.getProperty("user.dir");
        dir=dir.replace("\\", "/");
            try {
                connection.messageSender.sendMessageToExpertSystem("set_current_directory('"+dir+"')");
                connection.messageSender.sendMessageToExpertSystem("load('"+rulesFilename+"','"+solutionsFilename+"')");

            } catch (InterruptedException ex) {
                Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
            }

    }//GEN-LAST:event_loadRulesButtonActionPerformed

    public void loadingSuccessful(){
        setFilenameWrongLabelText("");
        // move to main menu screen
        systemState = SystemStateEnum.MAIN_MENU;
        switchScreen();
    }
    
    public void switchScreen(){
        BorderLayout borderLayout = (BorderLayout) this.getContentPane().getLayout();
        Component centerComponent = borderLayout.getLayoutComponent(BorderLayout.CENTER);
        if(centerComponent != null)
            this.remove(centerComponent);
        
        switch(systemState){
            case START:
                getContentPane().add(startPanel, java.awt.BorderLayout.CENTER);
                this.revalidate();
                this.repaint();
                break;
            case MAIN_MENU:
                getContentPane().add(outputAreaPanel, java.awt.BorderLayout.CENTER);
                this.revalidate();
                this.repaint();
                break;
        }
    }
    
    private void getProofForSolution(String selectedSolution) {
        try {
            selectedSolution = selectedSolution.endsWith("cu fc 100") ?
                               selectedSolution.substring(0,selectedSolution.length()-10) :
                               selectedSolution.substring(0,selectedSolution.length()-9);
            
            String[] words = selectedSolution.split(" ");
            String message = String.join(",", words);
            message = "how([" + message + "])";
            
            proofTextPane.setText("");
            connection.messageSender.sendMessageToExpertSystem(message);
            proofScrollPane.setVisible(true);
            questionsPanel.revalidate();
            questionsPanel.repaint();
        }
        catch (InterruptedException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void switchToConsultView() {
        //this.commandPanel.setVisible(false);
        this.questionsPanel.setVisible(true);
        this.backToMenuButton.setVisible(false);
        this.consultButton.setEnabled(false);
        
        this.optionsPanel.setVisible(true);
        this.questionLabel.setVisible(true);
        this.certaintyFactorComboBox.setVisible(true);
        this.certaintyFactorLabel.setVisible(true);
        
        this.revalidate();
        this.repaint();
    }                                             

    private void switchToMenuView() {
        this.optionsPanel.removeAll();
        this.optionsPanel.repaint();
        this.optionsPanel.revalidate();
        
        this.questionLabel.setText("");
        
        this.commandPanel.setVisible(true);
        this.questionsPanel.setVisible(false);
    }                                            

    private void switchToSolutionView() {
        this.optionsPanel.setVisible(false);
        this.questionLabel.setVisible(false);
        this.certaintyFactorComboBox.setVisible(false);
        this.certaintyFactorLabel.setVisible(false);
    }

    
     private void optionButtonActionPerformed(java.awt.event.ActionEvent evt) {
         
        int certaintyFactor = Integer.parseInt(certaintyFactorComboBox.getSelectedItem().toString());
        String answer = ((JButton)(evt.getSource())).getText() + " fc " + certaintyFactor;
        try {
            connection.messageSender.sendStringToExpertSystem(answer);
        }
        catch (InterruptedException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        SaveQuestionAndAnswerAndAddRadioButton(evt.getActionCommand(), answer);
    }

    private void SaveQuestionAndAnswerAndAddRadioButton(String attributeQuestion, String answer) {
        String[] s = attributeQuestion.split("~");
        String attribute = s[0];
        String question = s[1];
        addAtribute(attribute, question, answer);
        
        JRadioButton radioButton = new JRadioButton(attribute);
        radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });
        questionsRadioButtonGroup.add(radioButton);
        questionsRadioButtonPanel.add(radioButton);
        questionsRadioButtonPanel.revalidate();
        questionsRadioButtonPanel.repaint();
    }
    
    public void addAtribute(String attribute, String question, String answer){
        List<String> list = Arrays.asList(question, answer);
        QandA.put(attribute, list);
    }
    
    
    private void radioButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String attribute = ((JRadioButton)(evt.getSource())).getText();
        List<String> questionAndAnswer = QandA.get(attribute);
        String question = "Q: " + questionAndAnswer.get(0);
        String answer = "A: " + questionAndAnswer.get(1);
        answer = answer.endsWith("fc 100") ? answer.substring(0,answer.length()-7) : answer;
        
        answersTextArea.setText(question + "\n" + answer);
        answersScrollPane.setVisible(true);
        questionsPanel.revalidate();
        questionsPanel.repaint();
    } 
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window("Verificare").setVisible(true);
                
            }
        });
    }

    public javax.swing.JTextArea getOutputTextArea(){
        return outputTextArea;
    }
    
    public void setConnection(PrologConnection connection){
        this.connection = connection;
    }
    public void setQuestionAndOptions(String question, String optionsString, String attribute){
        
        this.questionLabel.setText("<html><body style='width:100%'>"+question+"</html>");
        this.questionsPanel.repaint();
        
        this.optionsPanel.removeAll();
        this.optionsPanel.setLayout(new FlowLayout());
        
        optionsString = optionsString.trim();
        String[] options = optionsString.split(" ");
        
        for (int i = 0; i < options.length; i++) {
            
            String iconPath = "icons/icon" + (i+1) + ".png";
            ImageIcon imageIcon = createImageIcon(iconPath);
            
            JButton optionButton = new JButton(options[i], imageIcon); 
            String s = attribute + "~" + question;
            optionButton.setActionCommand(s);
            optionButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    optionButtonActionPerformed(evt);
                }
            });
            this.optionsPanel.add(optionButton);
        }
        this.optionsPanel.repaint();
        this.optionsPanel.revalidate();
        switchToConsultView();
    } 

     /** Returns an ImageIcon, or null if the path was invalid. */
    private ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }
     
    public void setSolution(String solution){
         if(solution.equals("done")){
             if(!solutions.isEmpty())
                addSolutionsToJList();
             else
                noSolutionsLabel.setVisible(true);
             
             return;
         }
        solutions.add(solution);
        
        switchToSolutionView();
    } 

    private void addSolutionsToJList() {
        DefaultListModel<String> listModel = new DefaultListModel<>();
        solutions.stream().forEach((s) -> {
            listModel.addElement(s);
        });
        solutionsList.setModel(listModel);
    }
    
    public void setProofText(String text){
        text = text.charAt(0) == ' ' ? text : "\n"+text;
        text = text.startsWith("regula") ? "\n"+text : text;
        Document doc = proofTextPane.getDocument();
        try {
            doc.insertString(doc.getLength(), text, null);
        } 
        catch (BadLocationException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane answersScrollPane;
    private javax.swing.JTextArea answersTextArea;
    private javax.swing.JButton backToMenuButton;
    private javax.swing.JComboBox<String> certaintyFactorComboBox;
    private javax.swing.JLabel certaintyFactorLabel;
    private javax.swing.JPanel commandPanel;
    private javax.swing.JButton consultButton;
    private javax.swing.JLabel filenameWrongLabel;
    private javax.swing.JLabel greetingMessageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loadInfoLabel;
    private javax.swing.JButton loadRulesButton;
    private javax.swing.JLabel noSolutionsLabel;
    public javax.swing.JPanel optionsPanel;
    private javax.swing.JPanel outputAreaPanel;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JScrollPane proofScrollPane;
    private javax.swing.JTextPane proofTextPane;
    public javax.swing.JLabel questionLabel;
    private javax.swing.JPanel questionsPanel;
    private javax.swing.ButtonGroup questionsRadioButtonGroup;
    private javax.swing.JPanel questionsRadioButtonPanel;
    private javax.swing.JButton resetSystemButton;
    private javax.swing.JLabel rulesFilenameLabel;
    private javax.swing.JTextField rulesFilenameTextField;
    private javax.swing.JLabel solutionsFilenameLabel;
    private javax.swing.JTextField solutionsFilenameTextField;
    private javax.swing.JList<String> solutionsList;
    private javax.swing.JScrollPane solutionsScrollPane;
    private javax.swing.JLabel startLabel;
    private javax.swing.JPanel startPanel;
    // End of variables declaration//GEN-END:variables

}
